# Generated by Django 4.1.2 on 2022-11-18 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SIPMapp', '0003_usuario_preguntasrespondidas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='QuizUsuario',
        ),
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='QuizUser',
        ),
    ]
