# Generated by Django 4.1.2 on 2022-11-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIPMapp', '0004_rename_usuario_quizusuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='QuizUser',
            new_name='quizUser',
        ),
    ]
