# Generated by Django 4.1.2 on 2022-11-18 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIPMapp', '0006_pregunta_max_puntaje_alter_elegirrespuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='quizUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='SIPMapp.quizusuario'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIPMapp.elegirrespuesta'),
        ),
    ]
