# Generated by Django 4.1.2 on 2022-11-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIPMapp', '0007_alter_preguntasrespondidas_quizuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la respuesta correcta?'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje Obtenido'),
        ),
    ]
