# Generated by Django 4.1.2 on 2022-11-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIPMapp', '0009_elegirrespuesta_mat021_iv1_pregunta_mat021_iv1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elegirrespuesta_mat021_iv1',
            old_name='correcta',
            new_name='correcta1',
        ),
        migrations.RenameField(
            model_name='elegirrespuesta_mat021_iv1',
            old_name='texto',
            new_name='texto1',
        ),
        migrations.RenameField(
            model_name='pregunta_mat021_iv1',
            old_name='max_puntaje',
            new_name='max_puntaje1',
        ),
        migrations.RenameField(
            model_name='pregunta_mat021_iv1',
            old_name='texto',
            new_name='texto1',
        ),
        migrations.RenameField(
            model_name='preguntasrespondidas_mat021_iv1',
            old_name='correcta',
            new_name='correcta1',
        ),
        migrations.RenameField(
            model_name='preguntasrespondidas_mat021_iv1',
            old_name='puntaje_obtenido',
            new_name='puntaje_obtenido1',
        ),
        migrations.RenameField(
            model_name='preguntasrespondidas_mat021_iv1',
            old_name='respuesta',
            new_name='respuesta1',
        ),
        migrations.RenameField(
            model_name='quizusuario_mat021_iv1',
            old_name='puntaje_total',
            new_name='puntaje_total1',
        ),
        migrations.RenameField(
            model_name='quizusuario_mat021_iv1',
            old_name='usuario',
            new_name='usuario1',
        ),
        migrations.RemoveField(
            model_name='elegirrespuesta_mat021_iv1',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas_mat021_iv1',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas_mat021_iv1',
            name='quizUser',
        ),
        migrations.AddField(
            model_name='elegirrespuesta_mat021_iv1',
            name='pregunta1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='SIPMapp.pregunta_mat021_iv1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntasrespondidas_mat021_iv1',
            name='pregunta1',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIPMapp.pregunta_mat021_iv1'),
        ),
        migrations.AddField(
            model_name='preguntasrespondidas_mat021_iv1',
            name='quizUser1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='intentos1', to='SIPMapp.quizusuario_mat021_iv1'),
            preserve_default=False,
        ),
    ]
